defaults:
  - _self_
  - candidate-generation: streetclip.yaml
  - geo-estimation: country-to-coord.yaml
  - location-ranking: random.yaml
  - metadata-extractor: empty.yaml 
  - streetview-image-scraper: empty.yaml
img: assets/paris.jpeg